[[redirects]]
from = "/api/demos"
to = "https://greekgamesstudios.com/demos.json"
status = 200
force = true

[[redirects]]
from = "/api/games"
to = "https://greekgamesstudios.com/games.json"
status = 200
force = true